// Element data for periodic table layout
// Positioning uses (row, col) with 1-based indexing matching standard table layout
export const ELEMENTS = [
  { symbol: "H", name: "Hydrogen", atomicNumber: 1, row: 1, col: 1, category: "nonmetal" },
  { symbol: "He", name: "Helium", atomicNumber: 2, row: 1, col: 18, category: "noble" },
  { symbol: "Li", name: "Lithium", atomicNumber: 3, row: 2, col: 1, category: "alkali" },
  { symbol: "Be", name: "Beryllium", atomicNumber: 4, row: 2, col: 2, category: "alkaline" },
  { symbol: "B", name: "Boron", atomicNumber: 5, row: 2, col: 13, category: "metalloid" },
  { symbol: "C", name: "Carbon", atomicNumber: 6, row: 2, col: 14, category: "nonmetal" },
  { symbol: "N", name: "Nitrogen", atomicNumber: 7, row: 2, col: 15, category: "nonmetal" },
  { symbol: "O", name: "Oxygen", atomicNumber: 8, row: 2, col: 16, category: "nonmetal" },
  { symbol: "F", name: "Fluorine", atomicNumber: 9, row: 2, col: 17, category: "halogen" },
  { symbol: "Ne", name: "Neon", atomicNumber: 10, row: 2, col: 18, category: "noble" },
  { symbol: "Na", name: "Sodium", atomicNumber: 11, row: 3, col: 1, category: "alkali" },
  { symbol: "Mg", name: "Magnesium", atomicNumber: 12, row: 3, col: 2, category: "alkaline" },
  { symbol: "Al", name: "Aluminium", atomicNumber: 13, row: 3, col: 13, category: "post-transition" },
  { symbol: "Si", name: "Silicon", atomicNumber: 14, row: 3, col: 14, category: "metalloid" },
  { symbol: "P", name: "Phosphorus", atomicNumber: 15, row: 3, col: 15, category: "nonmetal" },
  { symbol: "S", name: "Sulfur", atomicNumber: 16, row: 3, col: 16, category: "nonmetal" },
  { symbol: "Cl", name: "Chlorine", atomicNumber: 17, row: 3, col: 17, category: "halogen" },
  { symbol: "Ar", name: "Argon", atomicNumber: 18, row: 3, col: 18, category: "noble" },
  { symbol: "K", name: "Potassium", atomicNumber: 19, row: 4, col: 1, category: "alkali" },
  { symbol: "Ca", name: "Calcium", atomicNumber: 20, row: 4, col: 2, category: "alkaline" },
  { symbol: "Sc", name: "Scandium", atomicNumber: 21, row: 4, col: 3, category: "transition" },
  { symbol: "Ti", name: "Titanium", atomicNumber: 22, row: 4, col: 4, category: "transition" },
  { symbol: "V", name: "Vanadium", atomicNumber: 23, row: 4, col: 5, category: "transition" },
  { symbol: "Cr", name: "Chromium", atomicNumber: 24, row: 4, col: 6, category: "transition" },
  { symbol: "Mn", name: "Manganese", atomicNumber: 25, row: 4, col: 7, category: "transition" },
  { symbol: "Fe", name: "Iron", atomicNumber: 26, row: 4, col: 8, category: "transition" },
  { symbol: "Co", name: "Cobalt", atomicNumber: 27, row: 4, col: 9, category: "transition" },
  { symbol: "Ni", name: "Nickel", atomicNumber: 28, row: 4, col: 10, category: "transition" },
  { symbol: "Cu", name: "Copper", atomicNumber: 29, row: 4, col: 11, category: "transition" },
  { symbol: "Zn", name: "Zinc", atomicNumber: 30, row: 4, col: 12, category: "transition" },
  { symbol: "Ga", name: "Gallium", atomicNumber: 31, row: 4, col: 13, category: "post-transition" },
  { symbol: "Ge", name: "Germanium", atomicNumber: 32, row: 4, col: 14, category: "metalloid" },
  { symbol: "As", name: "Arsenic", atomicNumber: 33, row: 4, col: 15, category: "metalloid" },
  { symbol: "Se", name: "Selenium", atomicNumber: 34, row: 4, col: 16, category: "nonmetal" },
  { symbol: "Br", name: "Bromine", atomicNumber: 35, row: 4, col: 17, category: "halogen" },
  { symbol: "Kr", name: "Krypton", atomicNumber: 36, row: 4, col: 18, category: "noble" },
  { symbol: "Rb", name: "Rubidium", atomicNumber: 37, row: 5, col: 1, category: "alkali" },
  { symbol: "Sr", name: "Strontium", atomicNumber: 38, row: 5, col: 2, category: "alkaline" },
  { symbol: "Y", name: "Yttrium", atomicNumber: 39, row: 5, col: 3, category: "transition" },
  { symbol: "Zr", name: "Zirconium", atomicNumber: 40, row: 5, col: 4, category: "transition" },
  { symbol: "Nb", name: "Niobium", atomicNumber: 41, row: 5, col: 5, category: "transition" },
  { symbol: "Mo", name: "Molybdenum", atomicNumber: 42, row: 5, col: 6, category: "transition" },
  { symbol: "Tc", name: "Technetium", atomicNumber: 43, row: 5, col: 7, category: "transition" },
  { symbol: "Ru", name: "Ruthenium", atomicNumber: 44, row: 5, col: 8, category: "transition" },
  { symbol: "Rh", name: "Rhodium", atomicNumber: 45, row: 5, col: 9, category: "transition" },
  { symbol: "Pd", name: "Palladium", atomicNumber: 46, row: 5, col: 10, category: "transition" },
  { symbol: "Ag", name: "Silver", atomicNumber: 47, row: 5, col: 11, category: "transition" },
  { symbol: "Cd", name: "Cadmium", atomicNumber: 48, row: 5, col: 12, category: "transition" },
  { symbol: "In", name: "Indium", atomicNumber: 49, row: 5, col: 13, category: "post-transition" },
  { symbol: "Sn", name: "Tin", atomicNumber: 50, row: 5, col: 14, category: "post-transition" },
  { symbol: "Sb", name: "Antimony", atomicNumber: 51, row: 5, col: 15, category: "metalloid" },
  { symbol: "Te", name: "Tellurium", atomicNumber: 52, row: 5, col: 16, category: "metalloid" },
  { symbol: "I", name: "Iodine", atomicNumber: 53, row: 5, col: 17, category: "halogen" },
  { symbol: "Xe", name: "Xenon", atomicNumber: 54, row: 5, col: 18, category: "noble" },
  { symbol: "Cs", name: "Cesium", atomicNumber: 55, row: 6, col: 1, category: "alkali" },
  { symbol: "Ba", name: "Barium", atomicNumber: 56, row: 6, col: 2, category: "alkaline" },
  { symbol: "La", name: "Lanthanum", atomicNumber: 57, row: 9, col: 4, category: "lanthanide" },
  { symbol: "Ce", name: "Cerium", atomicNumber: 58, row: 9, col: 5, category: "lanthanide" },
  { symbol: "Pr", name: "Praseodymium", atomicNumber: 59, row: 9, col: 6, category: "lanthanide" },
  { symbol: "Nd", name: "Neodymium", atomicNumber: 60, row: 9, col: 7, category: "lanthanide" },
  { symbol: "Pm", name: "Promethium", atomicNumber: 61, row: 9, col: 8, category: "lanthanide" },
  { symbol: "Sm", name: "Samarium", atomicNumber: 62, row: 9, col: 9, category: "lanthanide" },
  { symbol: "Eu", name: "Europium", atomicNumber: 63, row: 9, col: 10, category: "lanthanide" },
  { symbol: "Gd", name: "Gadolinium", atomicNumber: 64, row: 9, col: 11, category: "lanthanide" },
  { symbol: "Tb", name: "Terbium", atomicNumber: 65, row: 9, col: 12, category: "lanthanide" },
  { symbol: "Dy", name: "Dysprosium", atomicNumber: 66, row: 9, col: 13, category: "lanthanide" },
  { symbol: "Ho", name: "Holmium", atomicNumber: 67, row: 9, col: 14, category: "lanthanide" },
  { symbol: "Er", name: "Erbium", atomicNumber: 68, row: 9, col: 15, category: "lanthanide" },
  { symbol: "Tm", name: "Thulium", atomicNumber: 69, row: 9, col: 16, category: "lanthanide" },
  { symbol: "Yb", name: "Ytterbium", atomicNumber: 70, row: 9, col: 17, category: "lanthanide" },
  { symbol: "Lu", name: "Lutetium", atomicNumber: 71, row: 9, col: 18, category: "lanthanide" },
  { symbol: "Hf", name: "Hafnium", atomicNumber: 72, row: 6, col: 4, category: "transition" },
  { symbol: "Ta", name: "Tantalum", atomicNumber: 73, row: 6, col: 5, category: "transition" },
  { symbol: "W", name: "Tungsten", atomicNumber: 74, row: 6, col: 6, category: "transition" },
  { symbol: "Re", name: "Rhenium", atomicNumber: 75, row: 6, col: 7, category: "transition" },
  { symbol: "Os", name: "Osmium", atomicNumber: 76, row: 6, col: 8, category: "transition" },
  { symbol: "Ir", name: "Iridium", atomicNumber: 77, row: 6, col: 9, category: "transition" },
  { symbol: "Pt", name: "Platinum", atomicNumber: 78, row: 6, col: 10, category: "transition" },
  { symbol: "Au", name: "Gold", atomicNumber: 79, row: 6, col: 11, category: "transition" },
  { symbol: "Hg", name: "Mercury", atomicNumber: 80, row: 6, col: 12, category: "transition" },
  { symbol: "Tl", name: "Thallium", atomicNumber: 81, row: 6, col: 13, category: "post-transition" },
  { symbol: "Pb", name: "Lead", atomicNumber: 82, row: 6, col: 14, category: "post-transition" },
  { symbol: "Bi", name: "Bismuth", atomicNumber: 83, row: 6, col: 15, category: "post-transition" },
  { symbol: "Po", name: "Polonium", atomicNumber: 84, row: 6, col: 16, category: "metalloid" },
  { symbol: "At", name: "Astatine", atomicNumber: 85, row: 6, col: 17, category: "halogen" },
  { symbol: "Rn", name: "Radon", atomicNumber: 86, row: 6, col: 18, category: "noble" },
  { symbol: "Fr", name: "Francium", atomicNumber: 87, row: 7, col: 1, category: "alkali" },
  { symbol: "Ra", name: "Radium", atomicNumber: 88, row: 7, col: 2, category: "alkaline" },
  { symbol: "Ac", name: "Actinium", atomicNumber: 89, row: 10, col: 4, category: "actinide" },
  { symbol: "Th", name: "Thorium", atomicNumber: 90, row: 10, col: 5, category: "actinide" },
  { symbol: "Pa", name: "Protactinium", atomicNumber: 91, row: 10, col: 6, category: "actinide" },
  { symbol: "U", name: "Uranium", atomicNumber: 92, row: 10, col: 7, category: "actinide" },
  { symbol: "Np", name: "Neptunium", atomicNumber: 93, row: 10, col: 8, category: "actinide" },
  { symbol: "Pu", name: "Plutonium", atomicNumber: 94, row: 10, col: 9, category: "actinide" },
  { symbol: "Am", name: "Americium", atomicNumber: 95, row: 10, col: 10, category: "actinide" },
  { symbol: "Cm", name: "Curium", atomicNumber: 96, row: 10, col: 11, category: "actinide" },
  { symbol: "Bk", name: "Berkelium", atomicNumber: 97, row: 10, col: 12, category: "actinide" },
  { symbol: "Cf", name: "Californium", atomicNumber: 98, row: 10, col: 13, category: "actinide" },
  { symbol: "Es", name: "Einsteinium", atomicNumber: 99, row: 10, col: 14, category: "actinide" },
  { symbol: "Fm", name: "Fermium", atomicNumber: 100, row: 10, col: 15, category: "actinide" },
  { symbol: "Md", name: "Mendelevium", atomicNumber: 101, row: 10, col: 16, category: "actinide" },
  { symbol: "No", name: "Nobelium", atomicNumber: 102, row: 10, col: 17, category: "actinide" },
  { symbol: "Lr", name: "Lawrencium", atomicNumber: 103, row: 10, col: 18, category: "actinide" },
];

export const CATEGORY_STYLES = {
  alkali: { label: "Alkali Metal" },
  alkaline: { label: "Alkaline Earth" },
  transition: { label: "Transition Metal" },
  post: { label: "Post Transition" },
  "post-transition": { label: "Post Transition" },
  metalloid: { label: "Metalloid" },
  nonmetal: { label: "Nonmetal" },
  halogen: { label: "Halogen" },
  noble: { label: "Noble Gas" },
  lanthanide: { label: "Lanthanide" },
  actinide: { label: "Actinide" },
};
